name: Better-District
version: 'v1.0'
main: com.top1.districtplugin.Main
api-version: 1.13
author: mimitokox_
website: https://www.migmahost.pl / https://dsc.gg/mimicode /
description: Plugin with districts for e.g. THE HUNGER GAMES

commands:
  districtadmin:
    description: Admin command
    aliases:
      - da
      - dadmin
      - bdadmin
  district:
    description: Player command
    aliases:
      - d
      - bd